const LOGIN_USER = "LOGIN_USER";
const ADD_USER = "ADD_USER";
const ADD_USER_ERROR = "ADD_USER_ERROR";
const DELETE_USER = "DELETE_USER";

export {
  LOGIN_USER,
  ADD_USER,
  ADD_USER_ERROR,
   DELETE_USER,
};
